dist: focal
sudo: true
language: cpp
compiler: gcc

cache:
    - apt

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-9
            - gcc-9
            - lcov
    coverity_scan:
        project:
            name: "leozz37/texugo"
            description: "Texugo is a simple message switch based on RabbitMQ and modern C++"
        notification_email: leonardoaugusto287@gmail.com
        build_command_prepend: "cov-configure --comptype gcc --compiler $COMPILER --template; cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=$COMPILER"
        build_command: "cmake --build build"
        branch_pattern: coverity_scan
    env:
        - COMPILER=g++-9
        - IS_COVERAGE_BUILD=1


script:
    - mkdir build && cd build
    - cmake -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 --coverage ..
    - make -j2
    - ctest -R texugo_tests -V -j2

after_success:
    - lcov --capture --directory . --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' --output-file coverage.info
    - lcov --list coverage.info
    - bash <(curl -s https://codecov.io/bash) -f coverage.info -t $CODECOV_TOKEN|| echo "Codecov did not collect coverage reports"

deploy:
    provider: script
    skip-cleanup: true
    script: bash scripts/travis-deploy.sh
    on:
        branch: master

notifications:
    email: false