global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
    monitor: 'codelab-monitor'

  scrape_configs:
    - job_name: 'texugo'
      scrape_interval: 5s
      static_configs:
        - targets:
            - ['localhost:8080']